version: '3'
services:
  spring-boot-app:
    container_name: springboot-boot-app
    image: kym9129/sns-project-springboot
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis

  nginx:
    container_name: nginx
    image: nginx:stable-alpine-slim
    ports:
      - "80:80"
    volumnes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spring-boot-app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6.0.20-alpine
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: