logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # 바인딩되는 값 출력
      springframework:
        jdbc:
          core: TRACE

spring:
  output:
    ansi:
      enabled: always # console color

  redis:
    host: localhost
    port: 6379
    key:
      post_like_prefix: "post:like:"

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fast_sns?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: sa
    password: 1234